import type { Metadata } from 'next'
import { Noto_Sans_KR } from 'next/font/google'

import './globals.css'
import { ModalProvider } from '@/app/_context/ModalContext'
import HeaderGNB from '@/layout/HeaderGNB'
import MainWrapper from '@/layout/MainWrapper'
import SidebarLNB from '@/layout/SidebarLNB'
import ReactQueryProviders from '@/providers/ReactQueryProvider'

const notoSansKR = Noto_Sans_KR({
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko">
      <body className={`${notoSansKR.className} flex h-screen flex-col antialiased`}>
        <ReactQueryProviders>
          <ModalProvider>
            <HeaderGNB />
            <div className="flex flex-1 overflow-hidden">
              <SidebarLNB />
              <MainWrapper>{children}</MainWrapper>
            </div>
          </ModalProvider>
        </ReactQueryProviders>
      </body>
    </html>
  )
}
