import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";
import "./globals.css";
import HeaderGNB from "@/layout/HeaderGNB";
import SidebarLNB from "@/layout/SidebarLNB";
import MainWrapper from "@/layout/MainWrapper";

const notoSansKR = Noto_Sans_KR({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${notoSansKR.className} antialiased`}>
        <HeaderGNB />
        <div className="flex">
          <SidebarLNB />
          <MainWrapper>{children}</MainWrapper>
        </div>
      </body>
    </html>
  );
}
